const learningQuotes = [
    "Live as if you were to die tomorrow. Learn as if you were to live forever. – Mahatma Gandhi",
    "The beautiful thing about learning is that no one can take it away from you. – B.B. King",
    "Tell me and I forget, teach me and I may remember, involve me and I learn. – Benjamin Franklin",
    "Education is not the filling of a pail, but the lighting of a fire. – William Butler Yeats",
    "A mind is like a parachute. It doesn’t work if it is not open. – Frank Zappa",
    "The more that you read, the more things you will know. The more that you learn, the more places you’ll go. – Dr. Seuss",
    "Change is the end result of all true learning. – Leo Buscaglia",
    "Learning is not attained by chance; it must be sought for with ardor and attended to with diligence. – Abigail Adams",
    "An investment in knowledge pays the best interest. – Benjamin Franklin",
    "Wisdom is not a product of schooling but of the lifelong attempt to acquire it. – Albert Einstein",
    "The expert in anything was once a beginner. – Helen Hayes",
    "Learning never exhausts the mind. – Leonardo da Vinci",
    "Curiosity is the wick in the candle of learning. – William Arthur Ward",
    "Anyone who stops learning is old, whether at twenty or eighty. Anyone who keeps learning stays young. – Henry Ford",
    "You don’t learn to walk by following rules. You learn by doing and falling over. – Richard Branson",
    "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice. – Brian Herbert",
    "The roots of education are bitter, but the fruit is sweet. – Aristotle",
    "Knowledge will bring you the opportunity to make a difference. – Claire Fagin",
    "Learning is a treasure that will follow its owner everywhere. – Chinese Proverb",
    "In learning, you will teach, and in teaching, you will learn. – Phil Collins",
    "Education is the most powerful weapon which you can use to change the world. – Nelson Mandela",
    "Learning is the only thing the mind never exhausts, never fears, and never regrets. – Leonardo da Vinci",
    "Develop a passion for learning. If you do, you will never cease to grow. – Anthony J. D’Angelo",
    "The capacity to learn is unlimited; the will to learn is what matters most. – Anonymous",
    "Man’s mind, once stretched by a new idea, never regains its original dimensions. – Oliver Wendell Holmes Jr.",
    "You are always a student, never a master. You have to keep moving forward. – Conrad Hall",
    "Learning is not compulsory… neither is survival. – W. Edwards Deming",
    "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge. – Stephen Hawking",
    "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
    "All the world is a laboratory to the inquiring mind. – Martin H. Fischer",
    "Education’s purpose is to replace an empty mind with an open one. – Malcolm Forbes",
    "Knowledge is power. Information is liberating. Education is the premise of progress, in every society, in every family. – Kofi Annan",
    "Never stop learning, because life never stops teaching. – Anonymous",
    "Learning without thought is labor lost; thought without learning is perilous. – Confucius",
    "Self-education is, I firmly believe, the only kind of education there is. – Isaac Asimov",
    "Your mind is a powerful thing. When you fill it with positive thoughts, your life will start to change. – Anonymous",
    "The illiterate of the 21st century will not be those who cannot read and write, but those who cannot learn, unlearn, and relearn. – Alvin Toffler",
    "What we learn with pleasure we never forget. – Alfred Mercier",
    "Education is the key to unlocking the world, a passport to freedom. – Oprah Winfrey",
    "Learning is a journey, not a destination. – Anonymous"
  ];

const quoteSection = document.querySelector(".quote");
quoteSection.innerText = learningQuotes[Math.floor(Math.random()*39)]